# Generated by Django 4.0.5 on 2022-07-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='내용')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('complete', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('important', models.BooleanField(default=False, verbose_name='중요도')),
            ],
        ),
    ]
